// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type File struct {
	ID        pgtype.UUID
	Filename  string
	Content   string
	Embedding pgvector.Vector
	CreatedAt pgtype.Timestamptz
	Deleted   pgtype.Bool
}
